blog/urls.py
from django.conf.urls import patterns, url

from blog import views

from django.conf import settings


urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^signup/$', views.signup, name='signup'),
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^blog/$', views.blog, name='blog'),
	url(r'^about/$', views.about, name='about'),
	url(r'^blog/newpost/$', views.newpost, name='newpost'),
	url(r'^blog/newannounce/$', views.newannounce, name='newannounce'),
	url(r'^blog/delete/(?P<post_id>\d+)/$', views.delete, name='delete'),
	url(r'^blog/update/(?P<post_id>\d+)/$', views.update, name='update'),
	url(r'^yomamaisfat/$', views.root, name='root'),
	url(r'^makeadmin/$', views.makeadmin, name='makeadmin'),
	url(r'^users/$', views.users, name='users'),
	# url(r'^explore/$', views.explore, name='explore'),
	# url(r'^build/$', views.build, name='build',)
	# url(r'^update_education/$', views.education, name='update_education'),
	# url(r'^update_experience/$', views.experience, name='update_experience'),
	# url(r'^update_honors/$', views.honors, name='update_honors',)
	# url(r'^update_skill_set/$', views.skillset, name='update_skill_set'),
	# url(r'^match/$', views.match, name='match'),
	# url(r'^generate/$', views.generate, name='generate'),
	# url(r'^add_skill/$', views.addskill, name='add_skill'),
	# url(r'^add_job/$', views.addjob, name='add_job'),
	# url(r'^generated/(?P<file_name>.*)/$', views.generated, name='generated'),
	# url(r'^display/(?P<file_name>.*)/$', views.display, name='display'),
	# url(r'^matched/(?P<file_name>.*)/$', views.matched, name='matched'),
	# url(r'^save_resume/$', views.save_resume, name='save_resume'),
	# url(r'^create_tag/$', views.create_tag, name='create_tag'),

	# url(r'^login/$', views.login, name='login'),
	# url(r'^blog/login/$', views.login, name='login_redirect'),
	# url(r'^logout/$', views.logout, name='logout'),
	# url(r'^blog/$', views.index, name='index'),
	# url(r'^blog/(?P<page_num>\d+)/$', views.index, name='index_num'),
	# url(r'^blog/newpost/$', views.newpost, name='newpost'),
	# url(r'^blog/update/(?P<post_id>\d+)/$', views.update, name='update'),
	# url(r'^blog/delete/(?P<post_id>\d+)/$', views.delete, name='delete'),
	# url(r'^blog/post/(?P<post_id>\d+)/$', views.post, name='post'),
	)

math-club/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'quickstart.views.home', name='home'),
    url(r'^', include('blog.urls', namespace="blog")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models

# Create your models here.
class User(models.Model):
	username = models.CharField(max_length=120)
	password = models.CharField(max_length=120)
	name = models.CharField(max_length=120)
	admin = models.BooleanField(default=False)
	root = models.BooleanField(default=False)
	def is_admin(self):
		print self.username
		print self.admin
		return self.admin
	def __unicode__(self):
		return self.username

class Post(models.Model):
	subject = models.CharField(max_length=120)
	subject_rendered = models.TextField(default="")
	author = models.ForeignKey(User)
	kind = models.CharField(default='post', max_length=120)
	link = models.CharField(default='', max_length=255)
	content = models.TextField()
	content_rendered = models.TextField(default="")
	date = models.DateTimeField('date created')
	date_str = models.CharField(max_length=120)
	deleted = models.BooleanField(default=False)
	# tags = models.ManyToManyField(Tag)
	def __unicode__(self):
		return self.subject

# class Tag(models.Model):
# 	descript = models.CharField(max_length=120)
# 	def __unicode__(self):
# 		return self.descript

blog/views.py
# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.exceptions import ObjectDoesNotExist
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.core.files import File
import os
import datetime
import hashlib

from blog.models import User, Post

def render_post(content):
	array_str = content.splitlines()
	new_content = ""
	for temp in array_str:
		if temp=="":
			new_content+="<br />\n"
		else:
			new_content+="<p>"+temp+"</p>\n"
	return new_content

def render_subject(subject, link):
	if link:
		subject ='<a href="'+link+'">'+subject+'</a>'
	subject = '<h3 class="topfix">'+subject+'</h3>'
	return subject

def get_user(request):
	if 'user' in request.session:
		user = User.objects.filter(username=request.session['user'])[0]
		return user
	return None

def newpost(request):
	if 'user' in request.session:
		if request.method == 'POST':
			if request.POST['subject'] and request.POST['content']:
				d = datetime.datetime.now()
				p = Post(subject=request.POST['subject'], subject_rendered=render_subject(request.POST['subject'], request.POST['link']),
					content=request.POST['content'], content_rendered=render_post(request.POST['content']), 
					date=d, date_str=d.strftime('%B %d, %Y'),
					author=get_user(request),
					link=request.POST['link'],
					kind='post'
					)
				p.save()
				return HttpResponseRedirect(reverse('blog:blog'))
			else:
				context={
					'subject': request.POST['subject'],
					'content': request.POST['content'],
					'error_message': "Please fill in all fields",
					'request': request,
					'url': reverse('blog:newpost'),
				}
				return render(request, 'blog/newpost.html', context)
		return render(request, 'blog/newpost.html', {'request': request, 'url': reverse('blog:newpost')})
	else:
		return HttpResponseRedirect(reverse('blog:index'))

def root(request):
	if 'user' in request.session:
		print User.objects.filter(root=True)
		rooted = User.objects.filter(root=True)
		if not rooted:
			user = User.objects.filter(username=request.session['user'])[0]
			user.root = True
			user.admin = True
			user.save()
	return HttpResponseRedirect(reverse('blog:index'))


def newannounce(request):
	if 'user' in request.session:
		if request.method == 'POST':
			if request.POST['subject'] and request.POST['content']:
				d = datetime.datetime.now()
				p = Post(subject=request.POST['subject'],subject_rendered=render_subject(request.POST['subject'], request.POST['link']), 
					content=request.POST['content'], content_rendered=render_post(request.POST['content']), 
					date=d, date_str=d.strftime('%B %d, %Y'),
					author=get_user(request),
					link=request.POST['link'],
					kind='announce'
					)
				p.save()
				return HttpResponseRedirect(reverse('blog:index'))
			else:
				context={
					'subject': request.POST['subject'],
					'content': request.POST['content'],
					'error_message': "Please fill in all fields",
					'request': request,
					'url': reverse('blog:newannounce'),
				}
				return render(request, 'blog/newpost.html', context)
		return render(request, 'blog/newpost.html', {'request': request, 'url': reverse('blog:newannounce')})
	else:
		return HttpResponseRedirect(reverse('blog:index'))

def index(request):
	posts = Post.objects.order_by('-date').filter(kind='announce').filter(deleted=False)
	admin = ''
	if 'user' in request.session:
		user = get_user(request)
		if user.admin:
			admin = 'yay'
	return render(request, 'blog/index.html', {'request':request, 'nav': 'home', 'posts':posts, 'admin':admin})

def users(request):
	users = User.objects.all()
	return render(request, 'blog/users.html', {'request':request, 'users':users})

def blog(request):
	posts = Post.objects.order_by('-date').filter(kind='post').filter(deleted=False)
	return render(request, 'blog/blog.html', {'request':request, 'nav': 'blog', 'posts': posts})

def about(request):
	return render(request, 'blog/about.html', {'request':request, 'nav': 'about'})

def makeadmin(request):
	if request.method == 'POST':
		if 'username' in request.POST:
			user1 = User.objects.filter(username=request.POST['username'])[0]
			user1.admin = True
			user1.save()
		return HttpResponseRedirect(reverse('blog:index'))
	user = get_user(request)
	if user.root:
		return render(request, 'blog/makeadmin.html', {'request': request})
	else:
		return HttpResponseRedirect(reverse('blog:index'))

def signup(request):
	if request.method == 'POST':
		context={
			'username': request.POST['username'],
			'name': request.POST['name'],
			'request':request,
		}
		if request.POST['name'] and request.POST['username'] and request.POST['password'] and request.POST['password_confirm']:
			# d = datetime.datetime.now()
			if request.POST['password'] == request.POST['password_confirm']:
				u = User(username=request.POST['username'],
					password=hashlib.sha224(request.POST['password']+'key').hexdigest(),
					name=request.POST['name'],
					# date=d,
					# date_str=d.strftime('%B %d, %Y')
				)
				u.save()
				request.session['user'] = u.username
				request.session['user_obj'] = u
				return HttpResponseRedirect(reverse('blog:index'))
			context['error_message'] = 'Password mismatch'
		else:
			context['error_message'] = 'Please fill in all fields'
		return render(request, 'blog/signup.html', context)
	return render(request, 'blog/signup.html', {'request': request})

def login(request):
	context = {'request': request}
	if request.method == 'POST':
		userexists = False
		if request.POST['username']:
			try:
				user = User.objects.filter(username=request.POST['username'])[0]
				userexists = True
			except ObjectDoesNotExist:
				pass
		hashed_pass = ''
		if request.POST['password']:
			hashed_pass = hashlib.sha224(request.POST['password']+'key').hexdigest()
		if userexists and hashed_pass == user.password:
			request.session['user'] = user.username
			request.session['user_obj'] = user
			return HttpResponseRedirect(reverse('blog:index'))
		context['username'] = request.POST['username']
		context['error_message'] = "Username or password incorrect"
	return render(request, 'blog/login.html', context)


def logout(request):
	try:
		del request.session['user']
	except KeyError:
		pass
	return HttpResponseRedirect(reverse('blog:index'))

def delete(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	if 'user' in request.session and request.session['user'] == post.author.username:
		post.deleted = True
		post.save()
	return HttpResponseRedirect(reverse('blog:blog'))


def update(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	if 'user' in request.session and request.session['user'] == post.author.username:
		context={
			'post': post,	
			'url': reverse('blog:update', kwargs={'post_id': post_id}),
			'request': request,
		}
		if request.method == 'POST':
			if request.POST['subject'] and request.POST['content']:
				post.subject = request.POST['subject']
				post.content = request.POST['content']
				post.content_rendered = render_post(request.POST['content'])
				post.subject_rendered = render_subject(request.POST['subject'], request.POST['link'])
				post.save()
				if post.kind == 'post':
					return HttpResponseRedirect(reverse('blog:blog'))
				else:
					return HttpResponseRedirect(reverse('blog:index'))
			else:
				context['subject'] = request.POST['subject']
				context['content'] = request.POST['content']
				context['error_message'] = "Please fill in all fields<br />"
		return render(request, 'blog/update.html', context) 
	else:
		return HttpResponseRedirect(reverse('blog:index'))

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block jumbo %}
    <div class="jumbotron">
      <div class="container">
        <h1 class="topfix">About</h1>
        <p>Feel free to contact any of the officers for more info!</p>
      </div>
    </div>
{% endblock jumbo %}

{% block content %}
  <div class="row">
    <div class="col-lg-11 centered">
      <h1 class="topfix">Officers</h1>
      <div class="row">
        <div class="col-lg-11 centered">

          <br />
          <div class="row">
            <div class="col-lg-4 text-right">
              <h3 class="topfix">President</h3>
              <p>Jonathan Popa</p>
              <p>jmp108020@utdallas.edu</p>
            </div>
            <div class="col-lg-2">
              <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-prn1/c32.9.117.117/s100x100/72644_622983721052202_687655868_a.jpg" alt="President" class="img-rounded">
            </div>
            <div class="col-lg-2 text-right">
              <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-prn2/c11.9.108.108/s100x100/1185296_10200157155603142_2076894099_s.jpg" alt="Vice President" class="img-rounded">
            </div>
            <div class="col-lg-4">
              <h3 class="topfix">Vice President</h3>
              <p>Nathan Hudson</p>
              <p>neh092020@utdallas.edu</p>
            </div>
          </div>

         <br />
          <div class="row">
            <div class="col-lg-4 text-right">
              <h3 class="topfix">Secretary</h3>
              <p>Alec Brown</p>
              <p>japb101020@utdallas.edu</p>
            </div>
            <div class="col-lg-2">
              <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-prn1/c34.9.113.113/s100x100/404499_3039800069932_74371702_a.jpg" alt="Secretary" class="img-rounded">
            </div>
            <div class="col-lg-2 text-right">
              <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash3/c93.49.618.618/s100x100/484082_10151079411084360_1535701312_n.jpg" alt="Program Coordinator" class="img-rounded">
            </div>
            <div class="col-lg-4">
              <h3 class="topfix">Program Coordinator</h3>
              <p>Conner Davis</p>
              <p>conner.math.davis@gmail.com</p>
            </div>
          </div>         

          <br />
          <div class="row">
            <div class="col-lg-4 text-right">
              <h3 class="topfix">Webmaster</h3>
              <p>Josh Cai</p>
              <p>jxc124730@utdallas.edu</p>
            </div>
            <div class="col-lg-2">
              <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash2/c23.0.126.126/s100x100/1378195_10201213854681158_158181937_a.jpg" alt="Webmaster" class="img-rounded">
            </div>
            <div class="col-lg-2 text-right">
              <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash2/c1.0.129.129/s100x100/5216_1080519861980_2993051_s.jpg" alt="Faculty Advisor" class="img-rounded">
            </div>
            <div class="col-lg-4">
              <h3 class="topfix">Faculty Advisor</h3>
              <p>Dr. Paul Stanford</p>
              <p>paul.stanford@utdallas.edu</p>
            </div>
          </div>
          <br />

        </div>
      </div>
    </div>
  </div>


{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{% block title %}UTD Math Club{% endblock %}</title>
		<meta charset=”utf-8”> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="description" content="UTD Math Club">
	    <meta name="author" content="Josh Cai">
	    <!-- <link rel="shortcut icon" href="../../assets/ico/favicon.png"> -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap_journal.css' %}" media="screen">
		<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" media="screen">
	</head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'blog:index' %}">UTD Math Club</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li {% if nav == "home" %} class="active" {% endif %}><a href="{% url 'blog:index' %}">Home</a></li>
            <li {% if nav == "blog" %} class="active" {% endif %}><a href="{% url 'blog:blog' %}">Blog</a></li>
            <li {% if nav == "about" %} class="active" {% endif %}><a href="{% url 'blog:about' %}">About</a></li>
          </ul>
          {% if request.session.user %}
          <div class="navbar-form navbar-right">
          <a href="{% url 'blog:logout' %}"><button type="button" class="btn btn-info">Logout</button></a>
	      </div>
          {% else %}
          <div style="margin-left:0;padding-left:0" class="navbar-form navbar-right">
            <a href="{% url 'blog:signup' %}"><button class="btn btn-info">Sign Up</button></a>
          </div>
          <form style="padding-right:5px" action="{% url 'blog:login' %}" method="post" class="navbar-form navbar-right">
      			{% csrf_token %}
            <div class="form-group">
              <input type="text" name="username" placeholder="Username" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" name="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-info">Login</button>
          </form>
          {% endif %}
        </div><!--/.navbar-collapse -->
      </div>
    </div>
    {% block jumbo %}

    {% endblock jumbo %}

    <div class="container">
    	{% block content %}
    	{% endblock content %}
      <hr>

      <footer class="text-center">
        <p>&copy; UTD Math Club 2013</p>
      </footer>
    </div> <!-- /container -->



		<script src="http://code.jquery.com/jquery.js"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
    });
    </script>
    <script type="text/javascript" src="https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
	</body>
</html>

blog/templates/blog/blog.html
{% extends "blog/base.html" %}

{% block jumbo %}
    <div class="jumbotron">
      <div class="container">
        <h1 class="topfix">Blog</h1>
        <p>Post about interesting things in math here!</p>
      </div>
    </div>
{% endblock jumbo %}

{% block content %}
  <div class="row">
    <div class="col-lg-3 sidenav text-center">
      {% if request.session.user %}
        <a href="{% url 'blog:newpost' %}">New Post </a>
      {% else %}
        <h3>Signup to start posting!</h3>
        <form action="{% url 'blog:signup' %}" method="post">
          <fieldset>
            {% csrf_token %}
            <br />
            <!--<label>Subject</label>-->
            <input type="text" name="name" value="{{ name }}" placeholder="Name" class="form-control" />
            <br />
            <input type="text" name="username" value="{{ username }}" placeholder="Username" class="form-control" />
            <br />
            <!--<label>Content</label>-->
            <input type="password" name="password" placeholder="Password" class="form-control" />
            <br />
            <input type="password" name="password_confirm" placeholder="Password (confirm)" class="form-control"/>
            <br />
            {% if error_message %}
            <div class="alert alert-danger">{{ error_message | safe }}</div>
            {% endif %}
            <button type="submit" class="btn">Submit</button>
          </fieldset>
        </form>
      {% endif %}
    </div>
    <div style="padding-left:50px;" class="col-lg-9">
      {% for post in posts %}
      <br />
      <div class="row">
        <div class="col-lg-9">
          {{post.subject_rendered | safe}}
        </div>
        <div class="col-lg-3 text-right">
          <p>{{post.date_str}}</p>
          <p>{{post.author.username}}</p>
        </div>
      </div>
      {{post.content_rendered | safe}}
      {% if post.author.username == request.session.user %}
        <div class="text-right">
          <a href="{% url 'blog:delete' post.id %}">Delete</a>&nbsp;
          <a href="{% url 'blog:update' post.id %}">Update</a>
        </div>
      {% endif %}
      {% if not forloop.last %}
      <hr>
      {% endif %}
      {% endfor %}
    </div>
  </div>


{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block jumbo %}
    <div class="jumbotron">
      <div class="container">
        <h1 class="topfix">UTD Math Club</h1>
        <p>Join us on Wednesdays at 12:30pm in the Gemini Room!</p>
      </div>
    </div>
{% endblock jumbo %}

{% block content %}
  <div class="row">
    <div class="col-lg-6">
      <h1 class="topfix">Announcements</h1>
    </div>
    <div class="col-lg-6 text-right">
    {% if admin %}
      <a href="{% url 'blog:newannounce' %}">New Announcement </a>
    {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col-lg-11 centered">
      {% for post in posts %}
      <br />
      <div class="row">
        <div class="col-lg-9">
          {{post.subject_rendered | safe}}
        </div>
        <div class="col-lg-3 text-right">
          <p>{{post.date_str}}</p>
        </div>
      </div>
      {{post.content_rendered | safe}}
      {% if post.author.username == request.session.user %}
        <div class="text-right">
          <a href="{% url 'blog:delete' post.id %}">Delete</a>&nbsp;
          <a href="{% url 'blog:update' post.id %}">Update</a>
        </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>

{% endblock %}

blog/templates/blog/login.html
{% extends "blog/base.html" %}


{% block content %}
<br />
<div class="col-md-4 centered text-center">
	<form action="{% url 'blog:login' %}" method="post">
		<fieldset>
			{% csrf_token %}
			<h1>Login</h1>
			<!--<label>Subject</label>-->
			<input type="text" name="username" value="{{ user.name }}" placeholder="Username" class="form-control" />
			<br />
			<!--<label>Content</label>-->
			<input type="password" name="password" placeholder="Password" class="form-control" />
			<br />
			{% if error_message %}
			<div class="alert alert-danger">{{ error_message | safe }}</div>
			{% endif %}
			<button type="submit" class="btn">Submit</button>
		</fieldset>
	</form>
</div>
{% endblock %}

blog/templates/blog/makeadmin.html
{% extends "blog/base.html" %}


{% block content %}
<br />
<div class="col-md-6 centered text-center">
	<form action="{% url 'blog:makeadmin' %}" method="post">
		<fieldset>
			{% csrf_token %}
			<h1>Make Admin</h1>
			<!--<label>Subject</label>-->
			<input type="text" name="username"  placeholder="Username" class="form-control" />
			<br />
			<!--<label>Content</label>-->

			<button type="submit" class="btn">Submit</button>
		</fieldset>
	</form>
</div>
{% endblock %}

blog/templates/blog/newpost.html
{% extends "blog/base.html" %}


{% block content %}
<br />
<div class="col-md-6 centered text-center">
	<form action="{% url 'blog:newpost' %}" method="post">
		<fieldset>
			{% csrf_token %}
			<h1>New Post</h1>
			<!--<label>Subject</label>-->
			<input type="text" name="subject" value="{{ subject }}" placeholder="Title" class="form-control" />
			<br />
			<!--<label>Content</label>-->
			<textarea rows="20" cols="80" name="content" placeholder="Content" class="form-control">{{ content }}</textarea>
			<br />
			{% if error_message %}
			<div class="alert alert-danger">{{ error_message | safe }}</div>
			{% endif %}
			<button type="submit" class="btn">Submit</button>
		</fieldset>
	</form>
</div>
{% endblock %}

blog/templates/blog/signup.html
{% extends "blog/base.html" %}


{% block content %}
<br />
<div class="row">
	<div class="col-md-4 centered text-center">
		<form action="{% url 'blog:signup' %}" method="post">
			<fieldset>
				{% csrf_token %}
				<h1>Create an Account</h1>
				<br />
				<!--<label>Subject</label>-->
				<input type="text" name="name" value="{{ name }}" placeholder="Name" class="form-control" />
				<br />
				<input type="text" name="username" value="{{ username }}" placeholder="Username" class="form-control" />
				<br />
				<!--<label>Content</label>-->
				<input type="password" name="password" placeholder="Password" class="form-control" />
				<br />
				<input type="password" name="password_confirm" placeholder="Password (confirm)" class="form-control"/>
				<br />
				{% if error_message %}
				<div class="alert alert-danger">{{ error_message | safe }}</div>
				{% endif %}
				<button type="submit" class="btn">Submit</button>
			</fieldset>
		</form>
	</div>
</div>
{% endblock %}

blog/templates/blog/update.html
{% extends "blog/base.html" %}


{% block content %}
<br />
<div class="col-md-6 centered text-center">
	<form action="{{url}}" method="post">
		<fieldset>
			{% csrf_token %}
			<h1>Update</h1>
			<!--<label>Subject</label>-->
			<input type="text" name="subject" value="{{ post.subject }}" placeholder="Title" class="form-control" />
			<br />
			<input type="text" name="link" value="{{ post.link }}" placeholder="External Link (optional)" class="form-control" />
			<br />
			<!--<label>Content</label>-->
			<textarea rows="20" cols="80" name="content" placeholder="Content" class="form-control">{{ post.content }}</textarea>
			<br />
			{% if error_message %}
			<div class="alert alert-danger">{{ error_message | safe }}</div>
			{% endif %}
			<button type="submit" class="btn">Submit</button>
		</fieldset>
	</form>
</div>
{% endblock %}

blog/templates/blog/users.html
{% extends "blog/base.html" %}

{% block jumbo %}
    <div class="jumbotron">
      <div class="container">
        <h1 class="topfix">Users</h1>
        <p>See the list of users</p>
      </div>
    </div>
{% endblock jumbo %}

{% block content %}
  <div class="row">
    <div class="col-lg-11 centered">
      {% for user in users %}
      <br />
      {{user.username}} {{user.name}} 
      {% endfor %}
    </div>
  </div>

{% endblock %}